-- Solar incentive register seed — verified 2026-08-10 (agent research, sources per row)
-- Compliance model: informational rows are PUBLISHED but never monetized
-- (OTHER / REQUIRES_VERIFICATION are excluded from net cost by applyIncentives).
-- Programs with closed funding windows are DRAFT until re-verified.
-- Federal 25D is RETIRED to document the OBBBA termination explicitly.

INSERT INTO "SolarIncentiveProgram"
  (id, name, jurisdiction, "jurisdictionLevel", "stateCode", administrator,
   "incentiveType", "valueType", value, "eligibilitySummary", applicability,
   "homeownerRequirements", "effectiveFrom", "expiresOn",
   "sourceName", "sourceUrl", "lastVerifiedAt", "verifiedBy", status, notes, "createdAt", "updatedAt")
VALUES
  ('inc-fed-25d-retired',
   'Federal Residential Clean Energy Credit (IRC Section 25D) — terminated',
   'United States', 'FEDERAL', NULL, 'Internal Revenue Service',
   'Tax credit', 'PERCENT_OF_COST', 30,
   'Was a 30% federal tax credit for homeowner-owned solar placed in service through 2025-12-31. Terminated early by Public Law 119-21 (One Big Beautiful Bill Act, signed 2025-07-04). NOT available for any property placed in service after December 31, 2025. Credit earned on 2025 installations can still be claimed on the 2025 return and unused amounts carry forward.',
   'REQUIRES_VERIFICATION',
   '["System must have been placed in service on or before 2025-12-31", "Nonrefundable; carryforward allowed"]'::jsonb,
   '2022-01-01', '2025-12-31',
   'Internal Revenue Service — Residential Clean Energy Credit',
   'https://www.irs.gov/credits-deductions/residential-clean-energy-credit',
   '2026-08-10', 'agent-research', 'RETIRED',
   'Retained so stale 30% claims can be corrected with an authoritative termination date. IRS page states: "The credit is not available for any property placed in service after December 31, 2025."',
   NOW(), NOW()),

  ('inc-fed-48e-tpo',
   'Federal Clean Electricity Investment Credit (IRC Section 48E) — third-party-owned systems',
   'United States', 'FEDERAL', NULL, 'Internal Revenue Service',
   'Tax credit', 'OTHER', NULL,
   'Business-claimed investment tax credit that applies to third-party-owned (lease/PPA) residential solar, NOT to homeowner cash or loan purchases. Available for projects placed in service by 2027-12-31 (projects that began construction by 2026-07-04 may have until 2030-12-31). Savings may be passed through to the homeowner as a lower lease/PPA rate. Homeowners cannot claim this credit themselves.',
   'REQUIRES_VERIFICATION',
   '["Applies only to lease/PPA (third-party-owned) systems", "Credit belongs to the system owner, not the homeowner"]'::jsonb,
   '2025-01-01', '2027-12-31',
   'Internal Revenue Service — Credits and Deductions',
   'https://www.irs.gov/credits-deductions',
   '2026-08-10', 'agent-research', 'PUBLISHED',
   'Informational only; never monetized. Context for lease/PPA shoppers now that 25D is gone.',
   NOW(), NOW()),

  ('inc-md-srec',
   'Maryland Solar Renewable Energy Credits (SRECs)',
   'Maryland', 'STATE', 'MD', 'Maryland Public Service Commission',
   'Production incentive (tradable credits)', 'OTHER', NULL,
   'Registered system owners earn 1 SREC per 1,000 kWh generated, for up to 15 years from interconnection. SRECs are sold through aggregators or brokers; prices are market-driven (reported roughly $50-$90 per SREC in 2026). Under the Brighter Tomorrow Act (2024), rooftop systems 5 MW or smaller placed in service between 2024-07-01 and 2028-01-01 may qualify for Certified SRECs worth 1.5x the standard value. For leased/PPA systems, SREC ownership depends on the contract.',
   'POTENTIALLY_APPLICABLE',
   '["System must be registered with the MD PSC after interconnection", "PJM GATS registration within 30 days of state certification", "SREC income is market-priced and not guaranteed"]'::jsonb,
   '2008-01-01', NULL,
   'Maryland Energy Administration — Solar',
   'https://energy.maryland.gov/Pages/Info/renewable/solar.aspx',
   '2026-08-10', 'agent-research', 'PUBLISHED',
   'Production income over time, not an upfront cost reduction — never monetized into net cost. Market price range from 2026 aggregator/market reporting; verify current prices before quoting.',
   NOW(), NOW()),

  ('inc-md-sales-tax-exemption',
   'Maryland Sales and Use Tax Exemption — Solar Energy Equipment',
   'Maryland', 'STATE', 'MD', 'Comptroller of Maryland',
   'Sales tax exemption', 'OTHER', NULL,
   'Residential solar energy equipment is exempt from Maryland''s 6% sales and use tax, applied at the point of sale. This reduces the upfront price directly; estimate ranges shown by Renovessa are pre-tax, so this is informational rather than an additional deduction.',
   'POTENTIALLY_APPLICABLE',
   '["Applied automatically by the installer at purchase"]'::jsonb,
   NULL, NULL,
   'Comptroller of Maryland — Sales and Use Tax',
   'https://www.marylandtaxes.gov/business/sales-use/index.php',
   '2026-08-10', 'agent-research', 'PUBLISHED',
   'Informational only. Confirm the statutory reference (MD Tax-General) with the Comptroller before quoting a statute number.',
   NOW(), NOW()),

  ('inc-md-property-tax-exemption',
   'Maryland Property Tax Exemption — Solar Energy Systems',
   'Maryland', 'STATE', 'MD', 'Maryland Department of Assessments and Taxation',
   'Property tax exemption', 'OTHER', NULL,
   'Solar energy equipment is exempt from Maryland real property tax assessment: installing solar does not increase the homeowner''s property tax bill even though it may raise home value.',
   'POTENTIALLY_APPLICABLE',
   '["Applies automatically at assessment"]'::jsonb,
   NULL, NULL,
   'Maryland Department of Assessments and Taxation',
   'https://dat.maryland.gov/Pages/default.aspx',
   '2026-08-10', 'agent-research', 'PUBLISHED',
   'Informational only; does not change installation cost.',
   NOW(), NOW()),

  ('inc-md-msap-fy27',
   'Maryland Solar Access Program (MSAP) — income-qualified grant',
   'Maryland', 'STATE', 'MD', 'Maryland Energy Administration',
   'Grant', 'DOLLARS_PER_WATT', 0.75,
   'Grant of $750 per kW of installed DC capacity, up to $7,500, for income-qualified Maryland homeowners (household income up to 150% of area median). FY26 funding ($12M) was reported nearly exhausted and the application window closed 2026-06-05. A future funding cycle is anticipated but not confirmed as of 2026-08-10. DO NOT treat as available until MEA announces the next cycle.',
   'REQUIRES_VERIFICATION',
   '["Income-qualified (up to 150% AMI)", "Must use an MEA-approved contractor", "First-come, first-served funding"]'::jsonb,
   '2025-06-13', '2026-06-05',
   'Maryland Energy Administration',
   'https://energy.maryland.gov/Pages/Info/renewable/solar.aspx',
   '2026-08-10', 'agent-research', 'DRAFT',
   'Kept DRAFT: FY26 window closed and funding reported exhausted. Re-verify and PUBLISH only when MEA opens the FY27 cycle.',
   NOW(), NOW()),

  ('inc-md-bridge-fund',
   'Maryland Solar Access Bridge Fund — federal ITC gap program',
   'Maryland', 'STATE', 'MD', 'Maryland Energy Administration',
   'Grant', 'OTHER', NULL,
   '2026 gap program replacing part of the expired federal 25D credit for a narrow cohort: Maryland residents who applied to MSAP between 2025-07-01 and 2025-11-30, own their system (cash/loan), had it installed 2026-01-01 through 2026-05-30, did not claim the federal credit, and register for MD SRECs. Not available to new applicants outside that window as of 2026-08-10.',
   'REQUIRES_VERIFICATION',
   '["Prior MSAP application within the 2025 window", "Install completed 2026-01-01 to 2026-05-30", "Did not claim federal 25D"]'::jsonb,
   '2026-01-01', '2026-05-30',
   'Maryland Energy Administration — Solar Bridge Fund Details',
   'https://mea.maryland.gov/solar-bridge-fund-details',
   '2026-08-10', 'agent-research', 'DRAFT',
   'Eligibility window has passed for new projects. Keep DRAFT unless MEA announces an extension or successor.',
   NOW(), NOW()),

  ('inc-dc-srec',
   'DC Solar Renewable Energy Credits (SRECs)',
   'District of Columbia', 'STATE', 'DC', 'DC Department of Energy and Environment',
   'Production incentive (tradable credits)', 'OTHER', NULL,
   'DC-registered system owners earn 1 SREC per 1,000 kWh generated for up to 15 years. DC SRECs are the highest-valued in the region (reported roughly $350-$425 per SREC in 2026, market-driven and not guaranteed). Sold through aggregators/brokers.',
   'POTENTIALLY_APPLICABLE',
   '["System must be registered in the District", "SREC income is market-priced and not guaranteed"]'::jsonb,
   NULL, NULL,
   'DC Department of Energy and Environment — Solar',
   'https://doee.dc.gov/solar',
   '2026-08-10', 'agent-research', 'PUBLISHED',
   'Production income, never monetized into net cost. ACP schedule phases down toward 2029; verify current market prices before quoting.',
   NOW(), NOW()),

  ('inc-dc-solar-for-all',
   'DC Solar for All — income-qualified no-cost solar',
   'District of Columbia', 'STATE', 'DC', 'DC Department of Energy and Environment',
   'Grant / no-cost installation', 'OTHER', NULL,
   'Income-qualified DC homeowners may receive rooftop solar at no cost through DOEE''s Solar for All initiative. Eligibility is income-based and program cycles/partners vary; confirm current availability and enrollment directly with DOEE.',
   'REQUIRES_VERIFICATION',
   '["DC resident, income-qualified", "Enrollment through DOEE or its program partners"]'::jsonb,
   NULL, NULL,
   'DC Department of Energy and Environment — Solar for All',
   'https://doee.dc.gov/service/solar-all',
   '2026-08-10', 'agent-research', 'PUBLISHED',
   'Informational; eligibility must be confirmed per household.',
   NOW(), NOW());
